import "@/fonts/line-awesome-1.3.0/css/line-awesome.min.css";
import "@/styles/index.scss";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "rc-slider/assets/index.css";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
